apiVersion: apps/v1
kind: Deployment

metadata:
  name: obbygate
  labels:
    app: obbygate

spec:
  replicas: 2

  selector:
    matchLabels:
      app: obbygate

  template:
    metadata:
      labels:
        app: obbygate

    spec:
      containers:
        - name: obbygate
          image: obbygate:0.1.0
          imagePullPolicy: ifnotpresent

          ports:
            - containerPort: 8000

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL